//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.Pages {
	
	
	public partial class EstadoAlterar {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label lblMensagem;
		
		protected System.Web.UI.WebControls.TextBox idEstado;
		
		protected System.Web.UI.WebControls.Button btnPesquisar;
		
		protected System.Web.UI.WebControls.Panel panelDetalhe;
		
		protected System.Web.UI.WebControls.TextBox nome;
	}
}
