//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.Pages {
	
	
	public partial class EstadoLista {
		
		protected System.Web.UI.HtmlControls.HtmlForm principal;
		
		protected System.Web.UI.WebControls.GridView gridListaEstado;
		
		protected System.Web.UI.WebControls.Label lblMensagem;
	}
}
